suppliers/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextField, \
    FloatField, FileField, PasswordField, BooleanField, SubmitField, IntegerField, TextAreaField, SelectField
from wtforms.validators import DataRequired
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from app_main.models import User, Direction, Who_number, Customer, Truck, Quantity, Truck_opt, Ttn, Customer_base
from flask_login import current_user
from wtforms.fields.html5 import DateField
from .models import *
from flask import session,g
from app_main.models import Request





def choice_supp():
    return Supplier.query

class formSupplier(FlaskForm):
    # name = QuerySelectField('Поставщик', query_factory=choice_supp, get_label='llc_name')
    name = SelectField('Имя', coerce=str)
    inn = StringField('INN', validators=[DataRequired()])
    check_inn = SelectField('INN', coerce=str)
    tora_red = SelectField('ТОРА или РЭД', choices=[('Тора', 'Тора'), ('РЭД', 'РЭД'), ('Гунвор', 'Гунвор')], validators=[DataRequired()])
    date_order_C = DateField('Дата заявки с клиентом', validators=[DataRequired()], default=datetime.today())
    date_loading_plan = DateField('Дата загрузки', validators=[DataRequired()])
    date_unloading_plan = DateField('Дата планируемой выгрузки', validators=[DataRequired()])
    
    #от поставщика
    s_invoice_number=StringField('Номер счета подрядчика')
    #полный перечень счетов
    s_n_all_invoices = SelectField('Все счета', coerce=str)
    s_inv_date = DateField('ДАТА')
    s_inv_das_inv_date_to_pay = DateField('ДАТА')
    s_inv_amount = IntegerField('Сумма счета подрячика')
    s_inv_vat = SelectField('НДС', choices=[(20, 20), ('БЕЗ НДС', 'БЕЗ НДС'), (0, 0)])
    s_inv_currency = SelectField('Валюта', choices=[('RUR', 'RUR'), ('EUR', 'EUR'), ('USD', 'USD')])
    s_inv_pay_day = DateField('ДАТА')
    s_payment_summ = IntegerField('Сумма  оплаты')
    bank = SelectField('Банк', choices=[('Модуль', 'Модуль'), ('Точка', 'Точка'), ('Альфа', 'Альфа'), ('УБИР', 'УБРИР')]) 

    ##на клиента
    c_inv_number = TextField('Номер счета на клиента')
    c_invoice_date = DateField('ДАТА')
    c_inv_amount = IntegerField('Сумма счета на клиента с НДС')
    c_inv_currency = SelectField('Валюта', choices=[('RUR', 'RUR'), ('EUR', 'EUR'), ('USD', 'USD')])
    c_inv_amount = IntegerField('Сумма счета на клиента')
    c_inv_plan_pay = DateField('ДАТА')

   
    

    photo = FileField()
    status=SelectField('СТАТУС', choices=[
        ('ЗАПЛАНИРОВАН', 'ЗАПЛАНИРОВАН'),
        ('В ПУТИ', 'В ПУТИ'),
        ('ДОСТАВЛЕН', 'ДОСТАВЛЕН')], validators=[DataRequired()])
    submit = SubmitField('Подтвердить')


#форма для поиска по ИНН
class formSupplierInn(FlaskForm):
     check_inn = SelectField('INN', coerce=str)
     submit = SubmitField('Подтвердить')

class formSupplierName(FlaskForm):
     name = SelectField('Имя', coerce=str)
     submit = SubmitField('Подтвердить Выбор')

class formSupplierInv(FlaskForm):
    supp_all_invoices = SelectField('Все счета', coerce=str)
    summ_pay = IntegerField('сумма платежа')
    transit = StringField('через кого платим')
    commision = SelectField('коммисия транзитера', choices=[
      (1, 1), (2, 2), (2.5, 2.5), (3.5, 3.5), (4, 4), (4.5, 4.5), (5, 5), (5.5, 5.5),(6, 6), (6.5, 6.5), (7, 7), (7.5, 7.5), (8, 8), (8.5, 8.5) 
      ], validators=[DataRequired()]
    )
    date_payment = DateField('Дата платежа')
    our_company = SelectField('наша компания',  coerce=str) 
    our_bank = SelectField('Банк', coerce=str) 
    
    
    submit = SubmitField('Подтвердить Выбор')



   



class PochtaForm(FlaskForm):
    pass

from flask_wtf import FlaskForm
from wtforms import SubmitField
from flask_wtf.file import FileField, FileAllowed, FileRequired

class UploadForm(FlaskForm):
    photo = FileField('Image', validators=[
        FileRequired(),
        
    ])
    submit = SubmitField('Submit')

class FormTransit(FlaskForm):
    innadd = StringField('ИНН')
    name_tr = SelectField('Имя', coerce=str)
    status_tr = SelectField('статус', coerce=str)
    date_send = DateField('ДАТА Отправки в транзит')
    date_recieved = DateField('Дата получения транзита')
    submit = SubmitField('Записать в базу')

#форма выставления счетов
class FormInvoices(FlaskForm):
    company = SelectField('ТОРА или РЭД', choices=[('Тора', 'Тора'), ('РЭД', 'РЭД'), ('Гунвор', 'Гунвор')], validators=[DataRequired()])
    c_invoice_date = DateField('ДАТА')
    c_inv_description = TextAreaField('Наименование')
    c_inv_amount = IntegerField('Сумма счета на клиента с НДС')
    c_inv_currency = SelectField('Валюта', choices=[('RUR', 'RUR'), ('EUR', 'EUR'), ('USD', 'USD')])
    vat = SelectField('НДС', choices=[(20, 20), ('БЕЗ НДС', 'БЕЗ НДС'), (0, 0)])
    c_inv_plan_pay = DateField('ДАТА')
    submit = SubmitField('Записать в базу')

suppliers/__init__.py
from flask import Blueprint, current_app, render_template

supp = Blueprint('supp', __name__, template_folder='templates', static_folder='static')

from suppliers import routes

suppliers/routes.py
from flask import render_template, request, \
    jsonify, redirect, flash, \
        send_from_directory, url_for, send_file, session, make_response, g, Response
from suppliers import supp
from .models import Supplier, Prefin, Documents, Tn, Supp_payment 
from app_main.models import *
from app_main import db, app
from .forms import *
from sqlalchemy import exc
from sqlalchemy import desc, or_, and_

from customers.models import *

import datetime
from datetime import timedelta
import json

from flask_login import current_user, login_required, login_user, logout_user

from .schema import UserObject, RequestObject, schema

from flask_graphql import GraphQLView


app.add_url_rule(
    '/graphql',
    view_func=GraphQLView.as_view(
        'graphql',
        schema=schema,
        graphiql=True
    )
)


@supp.route('/index')
def index():
    return jsonify({'test':'test'})


@supp.route('/add_supplier/<int:id>', methods=['GET', 'POST'])
def add_supplier(id):
    
    req = Request.query.get(id)
    session['id']=req.id
    fin = Prefin.query.filter(Prefin.req_id==session['id']).first()
    docs = Documents.query.filter(Documents.req_id==session['id'])
    id = req.id
    pick_up_date = req.pick_up_date
    


    
    
    z_id = session['id']
    z_doc = Zayvka.query.filter(Zayvka.req_id==z_id)
    print('z_doc is:' + str(z_id ))
    
    session['pick_up_date'] = pick_up_date

    new_id = session['id']
    print(new_id, pick_up_date)
    
    date = req.pick_up_date
    form=formSupplier()
    form.name.choices = [(g.llc_name, g.llc_name) for g in Supplier.query.all()]
    
    
    if fin:
        form.tora_red.data = fin.tora_red
        form.name.data = fin.supplier_name
        form.status.data = fin.status_of_request



    return render_template('add_supplier.html', form=form, req=req, date=date, docs=docs, fin=fin, z_doc=z_doc)

@supp.route('/add_supplier_to_db', methods=['POST', 'GET'])
def add_supplier_to_db():

    form=Supplier()
    name = request.args.get('name')
    form_inn = request.args.get('inn')
    
    

    print(name)
    new_supp = Supplier.query.filter_by(llc_name=name).first() or Supplier.query.filter_by(inn=form_inn).first()
    if new_supp:
         return jsonify({'error': 'поставщик уже есть в базе данных с таким именем или с ИНН'})

    elif not new_supp:
    
        print('dewde')
        new_supp = Supplier(llc_name=name, inn=form_inn)
        db.session.add(new_supp)
        db.session.commit()
        return jsonify({'success': 'Поставщик упешно внесен в базу данных'})
    


import os

from werkzeug.utils import secure_filename

APP_ROOT = os.path.dirname(os.path.abspath(__file__))

ALLOWED_EXTENSIONS = set(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif', 'pdf'])



def allowed_file(filename):
    return '.' in filename and \
        filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@supp.route('/new')
def new():
    return render_template("upload.html")

@supp.route('/upload', methods=['POST'])
def upload():
    target = os.path.join(APP_ROOT, 'documents/')
    r_id = request.args.get('req_id')
    print(r_id)
    if not os.path.isdir(target):
        os.mkdir(target)
    for file in request.files.getlist("file"):
        if file and allowed_file(file.filename):
            print(file)
            new_d = Documents(req_id=session['id'])
            db.session.add(new_d)
            db.session.commit()
            filename=str(new_d.req_id) + file.filename
            new_d.path=str(filename)
            db.session.commit()

            destination = "/".join([target, filename])
            print(destination)
            file.save(destination)
            return jsonify({'success':'файлы успешно сохранены'})
        else:
            return jsonify({'success':'файлы запрещен к загрузке'})




@supp.route('/download/<path:filename>', methods=['GET'])
def download_file(filename):
    return send_from_directory(os.path.join(APP_ROOT, 'documents/'),
                               filename, as_attachment=True)



@supp.route('/prefin', methods=['POST', 'GET'])
def prefin():
    transit = int(7)
    form = formSupplier()
    tora_red = request.args.get('name')
    req_id = request.args.get('id')
    date_request = request.args.get('date')
    customer_order_date=datetime.datetime.strptime(date_request, '%Y-%m-%d')
    supplier_name=request.args.get('supp')
    status_of_request = request.args.get('st')
    s_invoice_number = request.args.get('invoice_number')
    s_inv_amount =float(request.args.get('sinv_amount'))
    s_inv_vat = request.args.get('sinv_vat')
    c_inv_amount=int(request.args.get('cinv_amount'))
    supplier_id = Supplier.query.filter(Supplier.llc_name==supplier_name).first()
    pick_up_date = request.args.get('pick_up_date')
   
    unloading_date = request.args.get('unloading_date')
    s_inv_date = request.args.get('sinv_date')
    s_inv_currency = request.args.get('sinv_currency')
    s_inv_vat = request.args.get('sinv_vat')
    print('eto form.inv.date: ' +str(s_inv_currency) )
    if s_inv_vat=='НДС':
        cost_with_vat = round(s_inv_amount+(s_inv_amount*0.2),2)
    elif s_inv_vat=='БЕЗ НДС':
        cost_with_vat = round(s_inv_amount/0.93, 2)
    elif s_inv_vat=='НОЛЬ':
        cost_with_vat = s_inv_amount
        
    request_one=Request.query.get(req_id)
    direction = request_one.direction
    sale = request_one.user.name or current_user.name
    customer = request_one.customer.name
    buyer = request_one.users[0].name
    loading_place = request_one.org
    unloading_place  = request_one.dest
    
    s_inv_vat = s_inv_vat

    profit = cost_with_vat - c_inv_amount
    print('eto' + str(profit))

    try:
        if not Prefin.query.filter_by(req_id=req_id).first():
            print(tora_red + str(req_id) + ' ' + str(date_request)+''+str(supplier_name) + ''+ str(direction) + str(status_of_request))
            newFin = Prefin(tora_red=tora_red, 
                        req_id=req_id, 
                        request_id = req_id,
                        customer_order_date=customer_order_date,
                        direction=direction, 
                        sale=sale,
                        buyer = buyer,
                        customer_name=customer,
                        loading_place=loading_place,
                        unloading_place=unloading_place,
                        cargo_character = request_one.cargo_desciption,
                        supplier_name=supplier_id.llc_name,
                        status_of_request=status_of_request,
                        s_invoice_number=s_invoice_number,
                        s_inv_amount=s_inv_amount,
                        s_inv_vat = s_inv_vat,
                        c_inv_amount=int(c_inv_amount),
                        supplier_id = supplier_id.id,
                        loading_date = pick_up_date,
                        unloading_date = unloading_date,
                        s_inv_date = s_inv_date,
                        s_inv_currency = s_inv_currency,
                        cost_with_vat = cost_with_vat,
                        profit = c_inv_amount-cost_with_vat
                        
                        
                        )
            db.session.add(newFin)
            db.session.commit()
            newFin.supplier.append(supplier_id)
            supp_inv_draft = Supp_payment(s_inv_amount=s_inv_amount, supplier_id=supplier_id.id, fin_id=newFin.id)
            db.session.add(supp_inv_draft)
            

           
            request_one.complete_fin=1
            if request_one.zayvka.first():
                newFin.zayvka.append(request_one.zayvka.first())
                db.session.add(newFin)
                newFin.supplier.append(supplier_id)
                db.session.commit()
                
                return jsonify({'success':'данные успешно внесены в базу', 'req_id': newFin.id})
            else:
                db.session.add(newFin)
                db.session.commit()
                newFin.supplier.append(supplier_id)
                return jsonify({'success':'данные успешно внесены в базу но без заявки', 'req_id':  newFin.id})
              
           
        else:
            print('customer VGGFGF:' + customer)
            newFin=Prefin.query.filter_by(req_id=req_id).first()
            newFin.tora_red = tora_red,
            newFin.req_id=req_id,
            newFin.request_id = req_id,
            newFin.customer_order_date=customer_order_date,
            newFin.direction=direction, 
            newFin.sale=sale,
            newFin.buyer = buyer,
            newFin.customer_name=customer,
            newFin.cargo_character = request_one.cargo_desciption,
            
            newFin.supplier_name=supplier_id.llc_name,
            newFin.supplier_id = supplier_id.id,
            newFinloading_place=loading_place,
            newFin.unloading_place=unloading_place,
            newFin.status_of_request=status_of_request,
            newFin.s_invoice_number=s_invoice_number,
            newFin.s_inv_amount=s_inv_amount,
            newFin.s_inv_vat = s_inv_vat,
            newFin.c_inv_amount=int(c_inv_amount),
            
            newFin.loading_date = pick_up_date,
            newFin.unloading_date = unloading_date,
            newFin.s_inv_date = s_inv_date,
            newFin.s_inv_currency = s_inv_currency,
            newFin.cost_with_vat = cost_with_vat,
            newFin.profit = c_inv_amount- cost_with_vat
            if request_one.zayvka.first():
                newFin.zayvka.append(request_one.zayvka.first())
                newFin.supplier = []
                newFin.supplier.append(supplier_id)
                # newFin.supplier.first().supp_payment.append
                db.session.add(newFin)
                db.session.commit()
            else:
                newFin.supplier = []
                newFin.supplier.append(supplier_id)
                db.session.add(newFin)

suppliers/templates/add_supplier.html
{%extends 'base.html'%} {%block head%} {{super()}}
<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.4.js">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" /> {%endblock%} 


<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />

{%block content%}
<div id="successAlert" class="alert alert-success" role="alert" style="display:none;"></div>
<div id="errorAlert" class="alert alert-danger" role="alert" style="display:none;"></div>

<div class="mx-auto"  style='margin-left: 0.2cm;' >
    <form class="form-inline">
        
    <input type="text" placeholder="наименование поставщика" id='supp_name' name=name  class="form-control">
    <input type='text' placeholder='ati номер' id='ATI' , name='ati' class="form-control">
    
    <input type='text' placeholder='телефон' id='phone' , name='phone' class="form-control">
    <input type='text' placeholder='имя контакта' id='orginal' , name='name' class="form-control">
    {{form.inn(placeholder='ИНН', class="form-control")}}
   

    <button type="submit" class="btn btn-default" id='submit'>Записать в базу</button>
        
</form>
</div>


<div class>
    <script src="{{url_for('.static', filename='supp.js')}}"></script>
    <script src="{{url_for('.static', filename='add.js')}}"></script>

    <div id='content'>


        <div id="successAlert" class="alert alert-success" role="alert" style="display:none;">

        </div>
        <div id="errorAlert" class="alert alert-danger" role="alert" style="display:none;">

        </div>

        <table class="table table-sm">
            <thead>
                <tr>
                    <th>Действия</th>
                    <th>Работа №</th>
                    <th scope="col">ТОРА или РЭД</th>
                    <th scope="col">Наименование подрядчика</th>
                    <th scope="col">Статус</th>
                    <th scope="col">Direction</th>
                    <th scope="col">#</th>

                    <th scope="col">Продавец</th>
                    <th scope="col">Закупщик</th>
                    <th scope="col">Клиент</th>

                    <th scope="col">№ заявки с клиентом</th>
                    <th scope="col">дата заявки</th>
                    <th scope="col">Необходимая Грузоподъемность</th>
                    <th scope="col">место загрузки</th>


                    <th scope="col">когда загрузка</th>
                    <th scope="col">место выгрузки</th>
                    <th scope="col">когда выгрузка</th>
                    

                    <!-- <th scope="col">№ счета от подрядчика</th>
                    <th scope="col">дата счета</th> -->
                    <th scope="col">Кост от подрядчика, БЕЗ НДС</th>
                    <th scope="col">Размер НДС</th>
                    
                    <th scope="col">валюта счета Подрядчика</th>
                    <th scope="col">КОСТ Подрядчика с НДС</th>
                    <th scope="col">Продажа на клиента</th>
                    <th scope="col">Профит без почты</th>


                </tr>
                <tbody>
                    <tr>

                        <th>
                            {%if req.complete_fin !=1 %}
                            <form action="" , method='post' id='myform'>
                                <button type="submit">записать данные</button>
                            </form>
                            {%endif%} {%if req.complete_fin==1 %}
                            <form action="" , method='post' id='myform'>
                            <button type="submit">исправить данные</button>
                        </form> {%endif%}

                            </form>
                            <p></p>


                            <form id='my_form_id' action="{{url_for('supp.upload')}}" method="post" enctype="multipart/form-data" name='dedwed'>
                                <div>
                                    <label for="file"></label>
                                    <input type="file" id="file" name="file" multiple>
                                </div>
                                <div>
                                    <button>Submit</button>
                                </div>
                            </form>
                            <p>ТН, ТТН</p>
                            {%for d in docs%}
                            <p><a href="{{url_for('supp.download_file', filename=d.path)}}">{{d.path}}</a></p>
                            {%endfor%}

                            <p> Заявка от клиента или другие доки от продавца, см ниже:</p>
                            {%for d in z_doc%}
                            <p><a href="{{url_for('download_file', filename=d.path)}}">{{d.path}}</a>
                                <p>{%endfor%}
                                        {{ form.csrf_token()}}
                                    {%if req.prefin[0]%}
                                        <th id='prefin'><a href="{{url_for('supp.prefin_change_id_test', id=req.prefin[0].id)}}">{{req.prefin[0].id}}</a> </th>
                                    {%else%}
                                    <th id='prefin'></th>
                                    {%endif%}
                                        {%if fin.tora_red %}
                                    <th name='tora_red'>{{form.tora_red(value=fin.tora_red)}}</th>
                                    {%else%}
                                    <th name='tora_red'>{{form.tora_red}}</th>
                                    {%endif%}
                                    {%if fin.supplier_id%}
                                    <th name='name'>{{form.name(value=fin.supplier.llc_name)}}</th>
                                    {%else%}
                                    <th name='name'>{{form.name}}</th>
                                    {%endif%}
                                    <th>{{form.status}}</th>
                                    <th name='direction'>{{req.direction}}</th>
                                    <th name='id'>{{req.id}}</th>
                                    <th>{{req.user.name}}</th>
                                    <th> {{req.users[0].name}}</th>
                                    <th>{{req.customer.name}}</th>
                                    <th>{{req.id}}</th>
                                    <th><input type='text' value={{req.created}} onfocus="(this.type='date')" onblur="(this.type='text')" id='date_order_C'></th>
                                    <th>{{req.type_of_truck}}</th>
                                    <th>{{req.org}}</th>

                                    <th><input type='text' value={{req.pick_up_date}}  onfocus="(this.type='date')" onblur="(this.type='text')" id='date_loading_plan'></th>
                                    <th>{{req.dest}}</th>
                                    {%if fin.unloading_date%}
                                    <th><input type='text' value={{fin.unloading_date}} onfocus="(this.type='date')" onblur="(this.type='text')" id='date_unloading_date'></th>
                                    {%else%}
                                    <th><input type='text'  onfocus="(this.type='date')" onblur="(this.type='text')" id='date_unloading_date'></th>
                                    {%endif%}


                                    {%if fin.s_inv_amount%}
                                    <th>{{form.s_inv_amount(value=fin.s_inv_amount)}}</th>
                                    {%else%}
                                    <th>{{form.s_inv_amount()}}</th>
                                    {%endif%}
                                    <th>{{form.s_inv_vat(value=fin.s_inv_vat)}}</th>
                                    <!-- <th>{{form.s_invoice_number(placeholder=fin.s_invoice_number)}}</th> -->
                                    <!-- {%if fin.s_inv_date%}
                                    <th>{{form.s_inv_date(value=fin.s_inv_date.strftime('%Y-%m-%d'))}}</th>
                                    {%else%} -->
                                    <!-- <th>{{form.s_inv_date}}</th>
                                    {%endif%} -->
                                    {%if fin.s_inv_currency%}
                                    <th>{{form.s_inv_currency(value=fin.s_inv_currency)}}</th>
                                    {%else%}
                                    <th>{{form.s_inv_currency}}</th>
                                    {%endif%}
                                    <th>{{fin.cost_with_vat}}</th>
                                    {%if fin.c_inv_amount%}
                                    <th>{{form.c_inv_amount(value=fin.c_inv_amount)}}</th>
                                    {%else%}
                                    <th>{{form.c_inv_amount}}</th>
                                    {%endif%}
                                    {%if fin.profit%}
                                    <th>{{fin.profit}}</th>
                                    {%endif%}


                                    
                    
                                </tr>

            </thead>

            {%if req.complete==1%}
            <button id=re_write>
                исправить
            </button> {%endif%}

            <div>

            </div>
          




            {%endblock%} {%block scripts%} {%endblock%}

suppliers/templates/all_suppliers.html
 {%extends 'base.html'%} {%block head%} {{super()}}
<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.4.js">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" /> {%endblock%} 


<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />

{%block content%}


<div id="successAlert" class="alert alert-success" role="alert" style="display:none;"></div>
<div id="errorAlert" class="alert alert-danger" role="alert" style="display:none;"></div>
<div class>
    <script src="{{url_for('.static', filename='supp.js')}}"></script>
    <script src="{{url_for('.static', filename='add.js')}}"></script>

    

        <div id="successAlert" class="alert alert-success" role="alert" style="display:none;">

        </div>
        <div id="errorAlert" class="alert alert-danger" role="alert" style="display:none;">
            </div>


     
        

        <table class="table table-sm">
        <thead>
            <tr>
                <th>Поиск по имени</th>
                <th>Поиск по ИНН</th>
                
            </tr>
        </thead>
        <tbody>
            <th>
                    <form action=""  method="POST">
                            {{ formName.csrf_token }}
                            
                            {{formName.name.label()}}{{formName.name}}
                            <input type="submit">
                    </form>
            
            </th>
            <th>
                    <form action=""  method="POST">
                            {{ formINN.csrf_token }}
                            {{formINN.check_inn.label()}}  {{formINN.check_inn}}
                            <input type="submit">
                    </form>

            </th>
        </tbody>
        </table>
       
        

        <div id='content'>

           

        <table class="table table-sm">
            
             <thead>
               
                <tr>
            
                        
                <th>Id перевоза</th>
                <th>Наименование</th>
                <th>ИНН</th>
                <th>Количество счетов</th>
                

              
          
    
            </tr>

            <tbody>
                {%for supp in supps%}
                <tr>
                  
                    <th>{{supp.id}}</th>
                   
                    <th>{{supp.llc_name}}</th>
                    <th>{{supp.inn}}</th>
                    <th>{{supp.supp_payment.count()}}</th>
                   
                   
           
                {%endfor%}



            {%endblock%} {%block scripts%} 
            {{super()}}
    {{moment.include_moment()}}
  {{moment.lang('ru')}}
            
            
            {%endblock%}

suppliers/templates/complete.html
<h1>Files save</h1>

suppliers/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Flask-Dropzone Demo: Parallel Upload</title>
  {{ dropzone.load_css() }}
  {{ dropzone.style('border: 2px dashed #0087F7; margin: 10%; min-height: 200;') }}
</head>
<body>
  {{ dropzone.create(action='supp.upload_s') }}
  {{ dropzone.load_js() }}
  {{ dropzone.config(default_message='Drop here!') }}


</body>
</html>

suppliers/templates/s_payment_calendar.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <link href='/static/static_1/fullcalendar/fullcalendar.css' rel='stylesheet' />
  <link href='/static/static_1/fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />
  <script src='/static/static_1/fullcalendar/lib/moment.min.js'></script>
  <script src='/static/static_1/fullcalendar/lib/jquery.min.js'></script>
  <script src='/static/static_1/fullcalendar/fullcalendar.min.js'></script>
 {%block content%} 
 <script>


  $(document).ready(function() {
    
    $('#calendar').fullCalendar({
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'month,basicWeek,basicDay'
      },
      editable: true,
      eventLimit: true, // allow "more" link when too many events
      events: {url: 'data'}
    });
    
  });
</script>
</head>
<body>

 <div id='calendar'></div>
</body>
{%endblock%}
</html>